version: '3.4'

services:
  identityapi:
    container_name: Identity-API
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityApi/Dockerfile
    depends_on:
      - db

  gamecollectionapi:
    container_name: GameCollection-API
    image: ${DOCKER_REGISTRY-}gamecollectionapi
    build:
      context: .
      dockerfile: GameCollectionApi/Dockerfile
    depends_on:
      - db
  
  db:
    container_name: MSSQL-DB
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"